CREATE TABLE IF NOT EXISTS rental_data (
    id BIGINT IDENTITY(0,1),
    sample_count DOUBLE PRECISION,
    studio_value DOUBLE PRECISION,
    one_room_value DOUBLE PRECISION,
    two_room_value DOUBLE PRECISION,
    three_room_value DOUBLE PRECISION ,
    four_room_value DOUBLE PRECISION,
    city_id INT,
    detailed_id INT,
    state VARCHAR(255),
    city VARCHAR(255),
    zipcode DOUBLE PRECISION,
    beds DOUBLE PRECISION,
    count DOUBLE PRECISION,
    min DOUBLE PRECISION,
    max DOUBLE PRECISION,
    avg DOUBLE PRECISION,
    median DOUBLE PRECISION,
    adjusted_rental_income DOUBLE PRECISION,
    median_night_rate DOUBLE PRECISION,
    median_occupancy DOUBLE PRECISION,
    PRIMARY KEY (id)
)